name: XcraftRegionMarket

main: me.INemesisI.XcraftRegionMarket.XcraftRegionMarket

version: 0.8

softdepend: [WorldGuard, Vault]

commands:
  rm:
    usage: /rm help
    
permissions:
    XcraftRegionMarket.Admin:
        children:
            XcraftRegionmarket.Save: true
            XcraftRegionmarket.Reload: true
            XcraftRegionMarket.Mod: true
            XcraftRegionMarket.GP.Create: true
            XcraftRegionMarket.GP.Edit: true
        description: Access to Admin commands
        default: op
    
    XcraftRegionMarket.Mod:
        children:
            XcraftRegionMarket.Player: true
            XcraftRegionMarket.Sell.All: true
            XcraftRegionMarket.Rent.All: true
            XcraftRegionMarket.Delete.All: true
            XcraftRegionMarket.Create: true
            XcraftRegionMarket.Buy: true
            XcraftRegionMarket.Rent: true
            XcraftRegionMarket.AddPlayer.Other: true
            XcraftRegionMarket.RemovePlayer.Other: true
            XcraftRegionMarket.GP.Use: true
            XcraftRegionMarket.GP.List: true
            XcraftRegionMarket.Edit.*: true
        description: Access to Mod commands
        default: false
        
    XcraftRegionMarket.Player:
        children:
            XcraftRegionMarket.Buy: true
            XcraftRegionMarket.Rent: true
            XcraftRegionMarket.Sell: true
            XcraftRegionMarket.AddPlayer: true
            XcraftRegionMarket.RemovePlayer: true
        description: Access to Player commands
        default: true
        
    XcraftRegionmarket.Save:
        description: Access to save the data to file
        default: false
    XcraftRegionmarket.Reload:
        description: Access to reload the data from file
        default: false
        
    XcraftRegionMarket.Buy:
        description: Access to buy regions
        default: false
        
    XcraftRegionMarket.Rent:
        description: Access to rent regions
        default: false
    XcraftRegionMarket.Rent.All:
        description: Access to rent all regions
        default: false
        
    XcraftRegionMarket.Sell:
        description: Access to sell regions
        default: false
    XcraftRegionMarket.Sell.All: 
        children:
            XcraftRegionMarket.Sell: true
        description: Access to sell all regions
        default: false
        
    XcraftRegionMarket.Delete: 
        description: Access to delete own regions
        default: false
    XcraftRegionMarket.Delete.All: 
        children:
            XcraftRegionMarket.Delete: true
        description: Access to delete other regions with other names
        default: false
        
    XcraftRegionMarket.Create: 
        description: Access to create MarketSigns
        default: false
        
    XcraftRegionMarket.AddPlayer:
        description: Access to add players to the own region
        default: false
        
    XcraftRegionMarket.AddPlayer.Other:
        children:
            XcraftRegionMarket.AddPlayer: true
        description: Access to add players to any region
        default: false
        
    XcraftRegionMarket.RemovePlayer:
        description: Access to add players to the own region
        default: false
        
    XcraftRegionMarket.RemovePlayer.Other:
        children:
            XcraftRegionMarket.RemovePlayer: true
        description: Access to remove players from any region
        default: false
        
    XcraftRegionMarket.GP.Use: 
        description: Access to use Globalprices
        default: false
    XcraftRegionMarket.GP.List:
        description: Access to list Globalprices
        default: false
    XcraftRegionMarket.GP.Edit: 
        description: Access to edit Globalprices
        default: false
    XcraftRegionMarket.GP.Create: 
        description: Access to create / edit Globalprices
        default: false
        
    XcraftRegionMarket.Edit.*:
        children:
             XcraftRegionMarket.Edit.Type: true
             XcraftRegionMarket.Edit.Region: true
             XcraftRegionMarket.Edit.Price: true
             XcraftRegionMarket.Edit.Account: true
             XcraftRegionMarket.Edit.Intervall: true
             XcraftRegionMarket.Edit.Renter: true
        description: Access to edit MarketSigns
        default: false
        
    XcraftRegionMarket.Edit.Type:
        description: Access to edit the type
        default: false
    XcraftRegionMarket.Edit.Region:
        description: Access to edit the region
        default: false
    XcraftRegionMarket.Edit.Price:
        description: Access to edit the price
        default: false
    XcraftRegionMarket.Edit.Account:
        description: Access to edit the account
        default: false
    XcraftRegionMarket.Edit.Intervall:
        description: Access to edit the intervall
        default: false
    XcraftRegionMarket.Edit.Renter:
        description: Access to edit the renter
        default: false
        
        